spring.application.name=groups-service

spring.datasource.url=jdbc:postgresql://localhost:5432/groups_db
spring.datasource.username=groups_user
spring.datasource.password=groups_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true