spring.application.name=groups-service

spring.datasource.url=jdbc:postgresql://localhost:5432/groups_db?currentSchema=public&options=-c%20timezone=UTC
spring.datasource.username=groups_user
spring.datasource.password=groups_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true